# Generated by Django 5.2.5 on 2025-08-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(max_length=2)),
                ('religion', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('nearbylocation', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(max_length=5)),
                ('mobile', models.CharField(max_length=10)),
                ('alternate_mobile', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=500)),
                ('permanent_address', models.TextField(max_length=500)),
                ('dlnumber', models.CharField(max_length=20)),
                ('transport', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan',models.CharField(max_length=20)),
                ('uploadpan', models.FileField(upload_to='')),
                ('uploadaadhar', models.FileField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
                
            ],
        ),
    ]
