# Generated by Django 5.2.5 on 2025-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='drive',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
    ]
