# Generated by Django 5.2.5 on 2025-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0002_alter_drive_age_alter_drive_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='dlnumber',
            field=models.CharField(max_length=19),
        ),
    ]
