# Generated by Django 5.2.5 on 2025-08-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0003_alter_drive_dlnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('fathername', models.CharField(max_length=55)),
                ('religion', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('nearbylocation', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('alternate_mobile', models.CharField(max_length=10)),
                ('transport', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('pan', models.CharField(max_length=20)),
                ('uploadpan', models.FileField(upload_to='')),
                ('uploadaadhar', models.FileField(upload_to='')),
            ],
        ),
    ]
