# Generated by Django 5.2.5 on 2025-08-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cool', '0004_hire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
